apiVersion: consul.hashicorp.com/v1alpha1
kind: RouteAuthFilter
metadata:
  name: auth-filter
spec:
  jwt:
    providers:
    - name: my-dummy-jwt-provider
      verifyClaims:
      - path:
          - role
        value: admin

